task_name: 'dtlz3'
alg_name: 'default'

# -- Compute -- #
n_workers: 1

# -- Domain -- #
n_obj: 5
n_dof: 10
param_bounds: [0, 1]
desc_bounds:
- [0, 1]
- [0, 1]

desc_labels:
- Param 1
- Param 2

obj_labels:
- Obj 1
- Obj 2
- Obj 3
- Obj 4
- Obj 5


# -- MAP-Elites -- #
grid_res: [20, 20]
n_init: 200
n_gens: 1000
n_emitters: 2
n_batch: 100
iso_sigma:     [0.01, 0.01]
emitter_label: [0.01, 0.01]


# -- Logging -- #
print_rate:  10  # Print to console
plot_rate:   50  # Plot graphs
save_rate:   50  # Save archive

