exp_name: 'test'

# -- Compute -- #
n_workers: 1

# -- T-DominO -- #
hist_length: 10

# -- MAP-Elites -- #
grid_res: [20, 20]
n_init: 200
n_gens: 2000
n_emitters: 2
n_batch: 100
iso_sigma:     [0.01, 0.01]
emitter_label: [0.01, 0.01]

# -- Logging -- #
print_rate:  10  # Print to console
plot_rate:   100  # Plot graphs
save_rate:   1000  # Save archive